# ENTREGABLE SQL

## Conexión al laboratorio SQL

In [1]:
 !pip install sqlalchemy
 !pip install mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: mysql-connector-python in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (9.5.0)

In [2]:
from sqlalchemy import create_engine
import sqlalchemy
import mysql.connector as mysql
import pandas as pd

## Setting up the connection

In [3]:
# Parámetros de conexión
user     = 'root'
password = '031503'
db = 'entregable'
sqlServer = 'localhost' # debería ser IP o DNS (Domain Name System) del servidor de la base de datos

# Creamos string de conexión
connStr = "mysql+mysqlconnector://" + user + ":" + password + "@" + sqlServer  +  "/"  + db

# print de string de conexión
print (connStr)

# Conectamos con el servidor
conn = create_engine(connStr).connect()

mysql+mysqlconnector://root:031503@localhost/entregable

## Lectura de Excels

In [4]:

from sqlalchemy import text

dbs = conn.execute(text("SHOW DATABASES"))
for db in dbs:
    print(db)

('entregable',)
('information_schema',)
('mysql',)
('nuclio',)
('performance_schema',)
('sys',)

In [5]:
dbs.rowcount

6

In [6]:
print(dbs.fetchall())

[]

In [7]:
conn.exec_driver_sql("USE entregable")

In [8]:
pip install openpyxl --upgrade

Requirement already satisfied: openpyxl in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\matia\anaconda3\envs\nuevosql\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [31]:
df = pd.read_excel("Ficheros_entregable/ALOJAMIENTO.xlsx")
df.head(50)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75
2,ALOJ003,Cabaña El Refugio,1,1,NO,SI,NO,NO,45
3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
4,ALOJ005,Estudio Playa Blanca,1,1,NO,NO,SI,NO,40
5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60
8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
10,ALOJ011,Cabaña Bosque Encantado,1,2,NO,SI,NO,NO,65
11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
15,ALOJ016,Estudio Urbano,1,1,NO,NO,SI,NO,35
16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95
19,ALOJ020,Loft Estación Norte,1,1,SI,NO,SI,NO,55

In [30]:
df_precio = pd.read_excel("Ficheros_entregable/PRECIO.xlsx")
df_precio.head(50)

   CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0             ALOJ001             1800      SI                 100
1             ALOJ002              780      SI                  25
2             ALOJ003              800      NO                   0
3             ALOJ004             1600      SI                  25
4             ALOJ005              900      NO                   0
5             ALOJ006             1200      NO                   0
6             ALOJ007             1300      NO                   0
7             ALOJ008             1500      SI                  25
8             ALOJ009             1600      SI                 100
9             ALOJ010             1750      SI                  25
10            ALOJ011             1825      NO                   0
11            ALOJ012             1750      NO                   0
12            ALOJ013             1652      NO                   0
13            ALOJ014             1941      NO                   0
14            ALOJ015             1800      SI                  25
15            ALOJ016             2000      SI                  30
16            ALOJ017             2120      NO                   0
17            ALOJ018             1900      SI                  25
18            ALOJ019             1570      NO                   0
19            ALOJ020             1580      NO                   0

In [29]:
df_puntuacion = pd.read_excel("Ficheros_entregable/PUNTUACION.xlsx")
df_puntuacion.head(50)

   CODIGO_ALOJAMIENTO  PUNTOS            AGENCIA  PUNTOS_AGENCIA
0             ALOJ001     5.0         GlobalHome             4.4
1             ALOJ002     4.2         AndesRenta             4.1
2             ALOJ003     4.1       AlquilaFacil             4.0
3             ALOJ004     4.6         CaribeRent             4.6
4             ALOJ005     4.4           RentaTop             3.8
5             ALOJ006     4.3         TerraHouse             4.9
6             ALOJ007     4.9       SevillaRooms             4.5
7             ALOJ008     4.8          ChileVive             4.3
8             ALOJ009     4.7         MexicoRent             4.8
9             ALOJ010     4.8          UYAlquila             4.9
10            ALOJ011     4.0      MalagaTurismo             4.9
11            ALOJ012     4.2        CórdobaStay             4.6
12            ALOJ013     3.8         AndesElite             4.3
13            ALOJ014     4.7        BogotaLodge             4.5
14            ALOJ015     4.9  EasyStay Valencia             4.7
15            ALOJ016     4.3    PuntaAlquileres             4.4
16            ALOJ017     4.9         CuscoRenta             4.4
17            ALOJ018     4.7       MendozaRooms             4.7
18            ALOJ019     4.9            GDLRent             4.2
19            ALOJ020     4.9           VivaStay             4.9

In [32]:
df_ubicacion = pd.read_excel("Ficheros_entregable/UBICACION.xlsx")
df_ubicacion.head(50)

   CODIGO_ALOJAMIENTO      PAIS     CIUDAD  DIST_METRO  DIST_CENTRO
0             ALOJ001  Portugal      Liboa         1.0          2.0
1             ALOJ002    España     Madrid         0.5          0.8
2             ALOJ003    España  Barcelona         0.9          0.4
3             ALOJ004   Francia   Marsella         3.0          4.0
4             ALOJ005  Portugal     Oporto         4.0          3.0
5             ALOJ006   Francia      Paris         2.0          2.0
6             ALOJ007   Francia   Toulouse         1.0          3.0
7             ALOJ008    España  Barcelona         2.0          3.0
8             ALOJ009    España     Madrid         2.0          4.0
9             ALOJ010    España     Bilbao         2.0          5.0
10            ALOJ011    Italia      Milan         0.5          0.7
11            ALOJ012    Italia       Roma         1.0          0.8
12            ALOJ013    España    Sevilla         2.0          0.9
13            ALOJ014    Italia   Cerdegna         0.9          4.0
14            ALOJ015    España     Málaga         2.0          4.0
15            ALOJ016    Italia       Roma         2.0          2.0
16            ALOJ017   Francia      Paris         1.0          2.0
17            ALOJ018    España      Ibiza         2.0          4.0
18            ALOJ019  Portugal      Lagos         2.0          2.0
19            ALOJ020  Portugal    Madeira         3.0          2.0

In [13]:
df.to_sql("alojamiento",conn)

20

In [14]:
df_precio.to_sql("precio",conn)

ValueError: Table 'precio' already exists.

In [15]:
df_puntuacion.to_sql("puntuacion",conn)

ValueError: Table 'puntuacion' already exists.

In [16]:
df_ubicacion.to_sql("ubicacion",conn)

ValueError: Table 'ubicacion' already exists.

In [17]:
from sqlalchemy import text

In [18]:
conn.execute(text("SHOW TABLES")).fetchall()

[('alojamiento',), ('precio',), ('puntuacion',), ('ubicacion',)]

In [19]:
conn.execute(text("SELECT COUNT(*) FROM alojamiento")).fetchall()

[(20,)]

## Funciones a Utilizar para correr las querys de SQL en Python con VisualCode

In [ ]:
##sSQL = """ """
## conn.execute(text(sSQL)

In [ ]:
## sSQL= """
## """
## pd.read_sql(sSQL, conn)

In [ ]:
## conn.execute("SHOW TABLES").fetchall()

In [ ]:
## sSQL = """ SELECT MAX(precio) FROM products"""

##conn.execute(sSQL).fetchall()

In [ ]:
import sys
print(sys.executable)

# Enunciado

Trabajas en una agencia que se dedica a organizar viajes a personas, tu cargo específicamente es analista de datos del área de clientes VIP.
Ha llegado a la agencia un cantante famoso, conocido en España, que desea que le ubiquéis un buen alojamiento que le permita disfrutar del sol para sus próximas vacaciones de verano que serán a finales del mes de julio del 2025.
Este cliente quiere descansar porque necesita prepararse para una gira de conciertos que dará en septiembre y por ahora quiere alejarse del foco mediático todo lo que pueda durante sus vacaciones, no le gustaría llamar la atención durante esos días ya que estará con sus 2 padres, sus 2 hermanos pequeños, su novia y los padres de su novia.
El cliente no tiene claro el destino al que quiere ir, solo sabe que tiene que ser en alguna playa. Tu trabajo será encontrar la propiedad en la que el cliente y su familia se alojarán durante sus vacaciones de verano teniendo en cuenta las exigencias del cliente.

# Primera Parte

### Primer paso: crear la query de cada uno de las exigencias del cliente. Se debe crear una query para cada punto. (7 queries en total)

-El cliente exige terraza y aire acondicionado, pero no quiere piscina.

In [20]:
sSQL = """
SELECT * 
FROM alojamiento
WHERE TERRAZA = "SI" 
AND AIREC_ACOND = "SI" 
AND PISCINA = "NO";
 """
pd.read_sql(text(sSQL), conn)

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
1,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
2,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
3,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100

-No se alojará en estudios que no tengan salón ni en propiedades con solo un baño

In [22]:
sSQL = """
SELECT *
FROM alojamiento
WHERE SALON = "SI"
AND CANT_BANYOS > 1;
 """
pd.read_sql(text(sSQL), conn)

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
8,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
9,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
10,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
11,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

-La propiedad debe tener como mínimo 80m2

In [23]:
sSQL = """
SELECT *
FROM alojamiento
WHERE SUPERFICIE >= 80;
 """
pd.read_sql(text(sSQL), conn)

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
8,13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
9,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
10,16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
11,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
12,18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

-Como el cliente odia el ruido, no quiere alojarse en propiedades a menos de 1 km de una estación de metro ni a menos de 2 km del centro.

In [34]:
sSQL = """
SELECT *
FROM ubicacion
WHERE dist_metro >= 1
AND dist_centro >=2;
 """
pd.read_sql(text(sSQL), conn)

    index CODIGO_ALOJAMIENTO      PAIS     CIUDAD  DIST_METRO  DIST_CENTRO
0       0            ALOJ001  Portugal      Liboa         1.0          2.0
1       3            ALOJ004   Francia   Marsella         3.0          4.0
2       4            ALOJ005  Portugal     Oporto         4.0          3.0
3       5            ALOJ006   Francia      Paris         2.0          2.0
4       6            ALOJ007   Francia   Toulouse         1.0          3.0
5       7            ALOJ008    España  Barcelona         2.0          3.0
6       8            ALOJ009    España     Madrid         2.0          4.0
7       9            ALOJ010    España     Bilbao         2.0          5.0
8      14            ALOJ015    España     Málaga         2.0          4.0
9      15            ALOJ016    Italia       Roma         2.0          2.0
10     16            ALOJ017   Francia      Paris         1.0          2.0
11     17            ALOJ018    España      Ibiza         2.0          4.0
12     18            ALOJ019  Portugal      Lagos         2.0          2.0
13     19            ALOJ020  Portugal    Madeira         3.0          2.0

-El rango permitido por el cliente para pagar es entre 1.500€ y 2.000€ la noche.

In [26]:
sSQL = """
SELECT *
FROM precio
WHERE precio_alquiler BETWEEN 1500 AND 2000;;
 """
pd.read_sql(text(sSQL), conn)

    index CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0       0            ALOJ001             1800      SI                 100
1       3            ALOJ004             1600      SI                  25
2       7            ALOJ008             1500      SI                  25
3       8            ALOJ009             1600      SI                 100
4       9            ALOJ010             1750      SI                  25
5      10            ALOJ011             1825      NO                   0
6      11            ALOJ012             1750      NO                   0
7      12            ALOJ013             1652      NO                   0
8      13            ALOJ014             1941      NO                   0
9      14            ALOJ015             1800      SI                  25
10     15            ALOJ016             2000      SI                  30
11     17            ALOJ018             1900      SI                  25
12     18            ALOJ019             1570      NO                   0
13     19            ALOJ020             1580      NO                   0

-Como en anteriores ocasiones ha tenido problemas de intentos de estafas con otras agencias, el cliente pide que el % de reserva no sea muy alto, pero tampoco tan bajo (porque le genera inseguridad) por lo que propone un 25%

In [27]:
sSQL = """
SELECT *
FROM precio
WHERE porcentaje_reserva = 25;
 """
pd.read_sql(text(sSQL), conn)

   index CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0      1            ALOJ002              780      SI                  25
1      3            ALOJ004             1600      SI                  25
2      7            ALOJ008             1500      SI                  25
3      9            ALOJ010             1750      SI                  25
4     14            ALOJ015             1800      SI                  25
5     17            ALOJ018             1900      SI                  25

-Quiere que el alojamiento tenga más de 4,5 puntos de confianza y que la agencia que lo lleva tenga más de 4 puntos

In [33]:
sSQL = """
SELECT *
FROM puntuacion
WHERE puntos > 4.5
AND puntos_agencia > 4 ;
 """
pd.read_sql(text(sSQL), conn)

    index CODIGO_ALOJAMIENTO  PUNTOS            AGENCIA  PUNTOS_AGENCIA
0       0            ALOJ001     5.0         GlobalHome             4.4
1       3            ALOJ004     4.6         CaribeRent             4.6
2       6            ALOJ007     4.9       SevillaRooms             4.5
3       7            ALOJ008     4.8          ChileVive             4.3
4       8            ALOJ009     4.7         MexicoRent             4.8
5       9            ALOJ010     4.8          UYAlquila             4.9
6      13            ALOJ014     4.7        BogotaLodge             4.5
7      14            ALOJ015     4.9  EasyStay Valencia             4.7
8      16            ALOJ017     4.9         CuscoRenta             4.4
9      17            ALOJ018     4.7       MendozaRooms             4.7
10     18            ALOJ019     4.9            GDLRent             4.2
11     19            ALOJ020     4.9           VivaStay             4.9

### Segundo paso: crear en una única query la combinación de los filtros anteriores para hallar las propiedades que finalmente cumplen con todas las exigencias del cliente.

In [44]:
sSQL = """
SELECT *
FROM (
    SELECT 
        A.CODIGO_ALOJAMIENTO,
        A.NOMBRE,
        A.CANT_HAB,
        A.CANT_BANYOS,
        A.SUPERFICIE,
        A.TERRAZA,
        A.AIREC_ACOND,
        A.PISCINA,
        A.SALON,
        U.PAIS,
        U.CIUDAD,
        U.DIST_METRO,
        U.DIST_CENTRO,
        PR.PRECIO_ALQUILER,
        PR.PORCENTAJE_RESERVA,
        PU.PUNTOS,
        PU.PUNTOS_AGENCIA
    FROM ALOJAMIENTO AS A
    INNER JOIN PRECIO      AS PR ON A.CODIGO_ALOJAMIENTO = PR.CODIGO_ALOJAMIENTO
    INNER JOIN PUNTUACION  AS PU ON A.CODIGO_ALOJAMIENTO = PU.CODIGO_ALOJAMIENTO
    INNER JOIN UBICACION   AS U  ON A.CODIGO_ALOJAMIENTO = U.CODIGO_ALOJAMIENTO
) AS ALOJ
WHERE ALOJ.TERRAZA = 'SI'
  AND ALOJ.AIREC_ACOND = 'SI'
  AND ALOJ.PISCINA = 'NO'
  AND ALOJ.SALON = 'SI'
  AND ALOJ.CANT_BANYOS > 1
  AND ALOJ.SUPERFICIE >= 80
  AND ALOJ.DIST_METRO >= 1
  AND ALOJ.DIST_CENTRO >= 2
  AND ALOJ.PRECIO_ALQUILER BETWEEN 1500 AND 2000
  AND ALOJ.PORCENTAJE_RESERVA = 25
  AND ALOJ.PUNTOS_AGENCIA > 4.5
  AND ALOJ.PUNTOS > 4;

 ;
 """
pd.read_sql(text(sSQL), conn)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_HAB,CANT_BANYOS,SUPERFICIE,TERRAZA,AIREC_ACOND,PISCINA,SALON,PAIS,CIUDAD,DIST_METRO,DIST_CENTRO,PRECIO_ALQUILER,PORCENTAJE_RESERVA,PUNTOS,PUNTOS_AGENCIA
0,ALOJ004,Piso Centro Histórico,3,2,90,SI,SI,NO,SI,Francia,Marsella,3.0,4.0,1600,25,4.6,4.6
1,ALOJ010,Ático del Sol,3,3,88,SI,SI,NO,SI,España,Bilbao,2.0,5.0,1750,25,4.8,4.9
2,ALOJ015,Dúplex Las Rocas,4,3,120,SI,SI,NO,SI,España,Málaga,2.0,4.0,1800,25,4.9,4.7
3,ALOJ018,Piso Parque Central,4,2,100,SI,SI,NO,SI,España,Ibiza,2.0,4.0,1900,25,4.7,4.7

### Tercer paso: Como habéis visto, tenemos 4 propiedades que cumplen con todas las exigencias de nuestro cliente, ahora bien, desde tu punto de vista, haciendo un análisis de los datos del cliente y de todas sus exigencias ¿Cuál de estos 4 alojamientos le recomendarías y por qué?

In [49]:
sSQL = """
SELECT *
FROM (SELECT *
FROM (
    SELECT 
        A.CODIGO_ALOJAMIENTO,
        A.NOMBRE,
        A.CANT_HAB,
        A.CANT_BANYOS,
        A.SUPERFICIE,
        A.TERRAZA,
        A.AIREC_ACOND,
        A.PISCINA,
        A.SALON,
        U.PAIS,
        U.CIUDAD,
        U.DIST_METRO,
        U.DIST_CENTRO,
        PR.PRECIO_ALQUILER,
        PR.PORCENTAJE_RESERVA,
        PU.PUNTOS,
        PU.AGENCIA,
        PU.PUNTOS_AGENCIA
    FROM ALOJAMIENTO AS A
    INNER JOIN PRECIO      AS PR ON A.CODIGO_ALOJAMIENTO = PR.CODIGO_ALOJAMIENTO
    INNER JOIN PUNTUACION  AS PU ON A.CODIGO_ALOJAMIENTO = PU.CODIGO_ALOJAMIENTO
    INNER JOIN UBICACION   AS U  ON A.CODIGO_ALOJAMIENTO = U.CODIGO_ALOJAMIENTO
) AS ALOJ
WHERE ALOJ.TERRAZA = 'SI'
  AND ALOJ.AIREC_ACOND = 'SI'
  AND ALOJ.PISCINA = 'NO'
  AND ALOJ.SALON = 'SI'
  AND ALOJ.CANT_BANYOS > 1
  AND ALOJ.SUPERFICIE >= 80
  AND ALOJ.DIST_METRO >= 1
  AND ALOJ.DIST_CENTRO >= 2
  AND ALOJ.PRECIO_ALQUILER BETWEEN 1500 AND 2000
  AND ALOJ.PORCENTAJE_RESERVA = 25
  AND ALOJ.PUNTOS_AGENCIA > 4.5
  AND ALOJ.PUNTOS > 4) AS RES
  WHERE CANT_HAB >= 4
  ORDER BY PUNTOS DESC;
 """
pd.read_sql(text(sSQL), conn)

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_HAB,CANT_BANYOS,SUPERFICIE,TERRAZA,AIREC_ACOND,PISCINA,SALON,PAIS,CIUDAD,DIST_METRO,DIST_CENTRO,PRECIO_ALQUILER,PORCENTAJE_RESERVA,PUNTOS,AGENCIA,PUNTOS_AGENCIA
0,ALOJ015,Dúplex Las Rocas,4,3,120,SI,SI,NO,SI,España,Málaga,2.0,4.0,1800,25,4.9,EasyStay Valencia,4.7
1,ALOJ018,Piso Parque Central,4,2,100,SI,SI,NO,SI,España,Ibiza,2.0,4.0,1900,25,4.7,MendozaRooms,4.7

Le recomendaría el alojamiento ALOJ015 Dúplex Las Rocas porque, además de cumplir con todas las exigencias del cliente, es una de las pocas opciones que ofrece cuatro habitaciones, lo que garantiza una estancia más cómoda para un grupo de ocho personas, y entre las dos propiedades que cumplen todos los requisitos y cuentan con esa capacidad, resulta ser la alternativa más económica dentro del rango permitido y también la que presenta la mejor puntuación (No habiendo diferencia entre los puntos de confianza de la agencia, ambas con muy buen puntaje, teniendo en cuenta sus anteriores experiencias de intentos de estafas sufridos).

# Segunda Parte

Responde las siguientes preguntas (con su respectiva query)

-¿Cuál es la suma total de metros cuadrados de los alojamientos que tienen piscina?

In [54]:
sSQL = """
SELECT SUM(SUPERFICIE) AS SUMA_METROS_CUADRADOS
FROM alojamiento
WHERE piscina = "SI";
 """
pd.read_sql(text(sSQL), conn)

   SUMA_METROS_CUADRADOS
0                  850.0

-¿Cuál es el alojamiento con mayor superficie?

In [55]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE, SUPERFICIE
FROM alojamiento
ORDER BY SUPERFICIE DESC
LIMIT 1;
 """
pd.read_sql(text(sSQL), conn)

  CODIGO_ALOJAMIENTO                 NOMBRE  SUPERFICIE
0            ALOJ017  Chalet Jardín Secreto         180

-¿Cuál es el alojamiento con menor superficie?

In [56]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE, SUPERFICIE
FROM alojamiento
ORDER BY SUPERFICIE ASC
LIMIT 1;
 """
pd.read_sql(text(sSQL), conn)

  CODIGO_ALOJAMIENTO          NOMBRE  SUPERFICIE
0            ALOJ016  Estudio Urbano          35

-¿Cuántos alojamientos tienen salón?

In [57]:
sSQL = """
SELECT COUNT(SALON) AS CANTIDAD_DE_ALOJ_CON_SALON
FROM alojamiento
WHERE SALON = "SI";
 """
pd.read_sql(text(sSQL), conn)

   CANTIDAD_DE_ALOJ_CON_SALON
0                          16

-¿Cuántos alojamientos tienen terraza?

In [58]:
sSQL = """
SELECT COUNT(TERRAZA) AS CANTIDAD_DE_ALOJ_CON_TERRAZA
FROM alojamiento
WHERE TERRAZA = "SI";
 """
pd.read_sql(text(sSQL), conn)

   CANTIDAD_DE_ALOJ_CON_TERRAZA
0                            14

-¿Cuántos alojamientos hay por cada país según nuestra tabla de UBICACIÓN?

In [60]:
sSQL = """
SELECT PAIS, COUNT(CODIGO_ALOJAMIENTO) AS CANTIDAD_DE_ALOJ_POR_PAIS
FROM UBICACION
GROUP BY PAIS;
 """
pd.read_sql(text(sSQL), conn)

       PAIS  CANTIDAD_DE_ALOJ_POR_PAIS
0  Portugal                          4
1    España                          8
2   Francia                          4
3    Italia                          4

-¿Cuál es el promedio de precios de alquiler de todos los alojamientos según la tabla PRECIO?

In [61]:
sSQL = """
SELECT AVG(PRECIO_ALQUILER) AS PRECIO_PROMEDIO_POR_NOCHE
FROM PRECIO;
 """
pd.read_sql(text(sSQL), conn)

   PRECIO_PROMEDIO_POR_NOCHE
0                     1568.4

-¿Cuáles son las 3 agencias que tienen la mayor puntuación de agencia (campo a usar: PUNTOS_AGENCIA) según la tabla PUNTUACION?

In [76]:
## EN ESTA QUERY SOLO TRAE TRES AGENCIAS PERO HAY 4 CON EL MISMO PUNTAJE
sSQL = """
SELECT AGENCIA, PUNTOS_AGENCIA
FROM PUNTUACION
ORDER BY PUNTOS_AGENCIA DESC
LIMIT 3
;
 """
pd.read_sql(text(sSQL), conn)

         AGENCIA  PUNTOS_AGENCIA
0     TerraHouse             4.9
1      UYAlquila             4.9
2  MalagaTurismo             4.9

In [77]:
## USANDO LA FUNCIÓN RANK()
sSQL = """
SELECT *
FROM (
    SELECT 
        AGENCIA,
        PUNTOS_AGENCIA,
        RANK() OVER (ORDER BY PUNTOS_AGENCIA DESC) AS rnk
    FROM puntuacion
) AS t
WHERE rnk <= 3
ORDER BY PUNTOS_AGENCIA DESC;

 """
pd.read_sql(text(sSQL), conn)

         AGENCIA  PUNTOS_AGENCIA  rnk
0     TerraHouse             4.9    1
1      UYAlquila             4.9    1
2  MalagaTurismo             4.9    1
3       VivaStay             4.9    1

-Muestra los alojamientos (código y nombre) que: Contengan la palabra ‘Piso’ en su nombre o que tengan piscina y aire acondicionado, pero no pasen los 150 metros de superficie o que tengan más de un baño

In [86]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE
FROM ALOJAMIENTO
WHERE (NOMBRE LIKE "%Piso%" OR (PISCINA = 'SI' AND AIREC_ACOND = 'SI'))
AND (SUPERFICIE <= 150 OR CANT_BANYOS > 1);
 """
pd.read_sql(text(sSQL), conn)

  CODIGO_ALOJAMIENTO                   NOMBRE
0            ALOJ001        Villa Sol del Mar
1            ALOJ004    Piso Centro Histórico
2            ALOJ006     Chalet Vista al Lago
3            ALOJ007  Dúplex Jardines del Sur
4            ALOJ012           Villa Palmeras
5            ALOJ014             Casa del Mar
6            ALOJ017    Chalet Jardín Secreto
7            ALOJ018      Piso Parque Central

-Muestra una consulta que muestre el código de alojamiento, el nombre, el precio y una columna donde veamos el precio del alquiler con el símbolo del euro al final de cada importe, esta nueva columna se debe llama PRECIO_MODIF

In [98]:
sSQL = """
SELECT 
    A.CODIGO_ALOJAMIENTO,
    A.NOMBRE,
    P.PRECIO_ALQUILER AS PRECIO,
    CONCAT(P.PRECIO_ALQUILER, ' €') AS PRECIO_MODIF
FROM ALOJAMIENTO AS A
INNER JOIN PRECIO AS P ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO;
 """
pd.read_sql(text(sSQL), conn)

   CODIGO_ALOJAMIENTO                    NOMBRE  PRECIO PRECIO_MODIF
0             ALOJ001         Villa Sol del Mar    1800       1800 €
1             ALOJ002  Apartamento Las Palmeras     780        780 €
2             ALOJ003         Cabaña El Refugio     800        800 €
3             ALOJ004     Piso Centro Histórico    1600       1600 €
4             ALOJ005      Estudio Playa Blanca     900        900 €
5             ALOJ006      Chalet Vista al Lago    1200       1200 €
6             ALOJ007   Dúplex Jardines del Sur    1300       1300 €
7             ALOJ008               Loft Urbano    1500       1500 €
8             ALOJ009      Casa Rústica Montaña    1600       1600 €
9             ALOJ010             Ático del Sol    1750       1750 €
10            ALOJ011   Cabaña Bosque Encantado    1825       1825 €
11            ALOJ012            Villa Palmeras    1750       1750 €
12            ALOJ013       Apartamento Moderno    1652       1652 €
13            ALOJ014              Casa del Mar    1941       1941 €
14            ALOJ015          Dúplex Las Rocas    1800       1800 €
15            ALOJ016            Estudio Urbano    2000       2000 €
16            ALOJ017     Chalet Jardín Secreto    2120       2120 €
17            ALOJ018       Piso Parque Central    1900       1900 €
18            ALOJ019            Casa Río Claro    1570       1570 €
19            ALOJ020       Loft Estación Norte    1580       1580 €

-Muestra una columna sobre la tabla PRECIO que se llame CATEGORIA_PRECIO y que indique la palabra ‘Bajo’ si el precio está entre 780 y 1000, ‘Medio’ si el precio está entre 1000 y 1700 y ‘Alto’ si es mayor a 1700

In [ ]:
sSQL = """
SELECT 
    *,
    CASE WHEN PRECIO_ALQUILER BETWEEN 780 AND 1000 THEN "BAJO"
         WHEN PRECIO_ALQUILER BETWEEN 1000 AND 1700 THEN "MEDIO"
         WHEN PRECIO_ALQUILER > 1700 THEN "ALTO"
         END AS CATEGORIA_PRECIO   
FROM PRECIO;
 """
pd.read_sql(text(sSQL), conn)

,index,CODIGO_ALOJAMIENTO,PRECIO_ALQUILER,RESERVA,PORCENTAJE_RESERVA,CATEGORIA_PRECIO
0,0,ALOJ001,1800,SI,100,ALTO
1,1,ALOJ002,780,SI,25,BAJO
2,2,ALOJ003,800,NO,0,BAJO
3,3,ALOJ004,1600,SI,25,MEDIO
4,4,ALOJ005,900,NO,0,BAJO
5,5,ALOJ006,1200,NO,0,MEDIO
6,6,ALOJ007,1300,NO,0,MEDIO
7,7,ALOJ008,1500,SI,25,MEDIO
8,8,ALOJ009,1600,SI,100,MEDIO
9,9,ALOJ010,1750,SI,25,ALTO
10,10,ALOJ011,1825,NO,0,ALTO
11,11,ALOJ012,1750,NO,0,ALTO
12,12,ALOJ013,1652,NO,0,MEDIO
13,13,ALOJ014,1941,NO,0,ALTO
14,14,ALOJ015,1800,SI,25,ALTO
15,15,ALOJ016,2000,SI,30,ALTO
16,16,ALOJ017,2120,NO,0,ALTO
17,17,ALOJ018,1900,SI,25,ALTO
18,18,ALOJ019,1570,NO,0,MEDIO
19,19,ALOJ020,1580,NO,0,MEDIO